version: "3.9"

services:
  mysql:
    image: mysql:5.7.35
    environment:
      MYSQL_ROOT_PASSWORD: urban
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - db:/var/lib/mysql
    platform: linux/x86_64
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:1.21.1
    depends_on:
      - mysql
      - php
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '3000:3000'
volumes:
  db:
